### ISSUE TITLE
Extra information in the pkbar

### ISSUE THREAD

**Issue by elsheikh21** [yueyericardo/pkbar#4]
Is there a way to add epoch number in the progress bar?

**Comment by yueyericardo** [comment]
Hi,

Now you could pass epoch (`epoch`) and total epochs (`num_epochs`) when initialize kbar. More information at [README.md](https://github.com/yueyericardo/pkbar/blob/master/README.md)

```
kbar = pkbar.Kbar(target=train_per_epoch, epoch=epoch, num_epochs=num_epochs, width=8, always_stateful=False)
```

which will print epoch number like below
```
Epoch: 1/3
```

Update your pkbar using: 
```
pip install pkbar --upgrade
```
#5
